env: local
http_server:
  addr: localhost:8083
  read_timeout: 4s
  write_timeout: 6s
  idle_timeout: 60s
postgresql:
  user: postgres
  password: postgrespw
  host: localhost
  port: 5432
  database: ushrt
